### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by junedgar** [ZCcaptain/rtsp_hw_decode#1]
您好：
　　感谢您的分享，能否请教一些问题？
　　１、下载[ffmpeg](https://github.com/FFmpeg/FFmpeg)后没有发现里面有include和lib文件夹；
　　２、除了ffmpeg include和lib没找到外，makefile以及相关mk环境都配置好。make的时候碰到错误：
` error: cannot convert ‘nvjpegStatus_t’ to ‘cudaError_t {aka cudaError}’ for argument ‘1’ to ‘const char* _cudaGetErrorEnum(cudaError_t)’ static_cast<unsigned int>(result), 　_cudaGetErrorEnum(result), func);`
　　能否给一些指导？
　　添麻烦啦！

**Comment by ZCcaptain** [comment]
ffmpeg要后自己手动带cuda参数编译安装
