### ISSUE TITLE
ModuleNotFoundError: No module named 'decode'

### ISSUE THREAD

**Issue by suneliw** [ZCcaptain/rtsp_hw_decode#2]
编译成功后运行 test_Capture.py 报错：ModuleNotFoundError: No module named 'decode' ，这个要怎么设置？

**Comment by ZCcaptain** [comment]
编译后的decode.so文件放在test_Capture.py同级目录下

**Comment by ZCcaptain** [comment]
> 编译成功后运行 test_Capture.py 报错：ModuleNotFoundError: No module named 'decode' ，这个要怎么设置？

编译后的decode.so文件放在test_Capture.py同级目录下
