### ISSUE TITLE
运行 test_Capture.py 报错：avcodec_find_decoder_by_name failed,  ffmpeg decode failed.

### ISSUE THREAD

**Issue by feifeiwei** [ZCcaptain/rtsp_hw_decode#4]
编译好以后， 读取数据流，出现avcodec_find_decoder_by_name failed,  ffmpeg decode failed. 的问题，请问是怎么回事呢？

**Comment by feifeiwei** [comment]
我发现问题是在decode.cpp里面，  nvidia硬解码部分 的codec 变量 值为NULL，执行的语句是codec = avcoder_find_decoder_by_name("hevc_cuvid")

**Comment by feifeiwei** [comment]
@ZCcaptain  请问有什么解决方法吗，谢谢

**Comment by ZCcaptain** [comment]
build成功后，可以查看目前ffmpeg所支持的nvidia硬件编解码器。
``` 
ffmpeg -codecs | grep cuvid
 ...
 DEV.L. h263                 H.263 / H.263-1996, H.263+ / H.263-1998 / H.263 version 2 (decoders: h263 h263_cuvid )
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_cuvid ) (encoders: h264_nvenc nvenc nvenc_h264 )
 DEV.L. hevc                 H.265 / HEVC (High Efficiency Video Coding) (decoders: hevc hevc_cuvid ) (encoders: nvenc_hevc hevc_nvenc )
 DEVIL. mjpeg                Motion JPEG (decoders: mjpeg mjpeg_cuvid )
 DEV.L. mpeg1video           MPEG-1 video (decoders: mpeg1video mpeg1_cuvid )
 DEV.L. mpeg2video           MPEG-2 video (decoders: mpeg2video mpegvideo mpeg2_cuvid )
 DEV.L. mpeg4                MPEG-4 part 2 (decoders: mpeg4 mpeg4_cuvid )
 D.V.L. vc1                  SMPTE VC-1 (decoders: vc1 vc1_cuvid )
 D.V.L. vp8                  On2 VP8 (decoders: vp8 vp8_cuvid )
 D.V.L. vp9                  Google VP9 (decoders: vp9 vp9_cuvid )
```
如果没有发现 hevc_cuvid，则需要重新编译ffmpeg，在编译时选择开启cuda支持.
参考[build ffmpeg with CUDA](https://www.jianshu.com/p/bf861b73bf65)
[ffmpeg](https://developer.nvidia.com/ffmpeg)

**Comment by feifeiwei** [comment]
重新编译ffmpeg，运行出现了

use_hw_decode:true, 
only_key_frame:false,
[udp @ 0x7fe3e000bbc0] ```attempted to set receive buffer to size 655360 but it only ended up set as 425984attempted to set receive buffer to size 655360 but it only ended up set as 425984duration:-9223372036854,```
fps:25.000000,
```[hevc_cuvid @ 0x7fe3e00a4200] Invalid pkt_timebase, passing timestamps as-is.```
width:2560,
height:1440,
src_codec_id:173,
codec_id:173,
src_pix_format:0,
codec_pix_format:23,
dest_pix_format:3,

**Comment by ZCcaptain** [comment]
#

> 重新编译ffmpeg，运行出现了
> 
> use_hw_decode:true,
> only_key_frame:false,
> [udp @ 0x7fe3e000bbc0] `attempted to set receive buffer to size 655360 but it only ended up set as 425984attempted to set receive buffer to size 655360 but it only ended up set as 425984duration:-9223372036854,`
> fps:25.000000,
> `[hevc_cuvid @ 0x7fe3e00a4200] Invalid pkt_timebase, passing timestamps as-is.`
> width:2560,
> height:1440,
> src_codec_id:173,
> codec_id:173,
> src_pix_format:0,
> codec_pix_format:23,
> dest_pix_format:3,

拉新代码试试

**Comment by feifeiwei** [comment]
> 拉新代码试试
新的编译通过后，运行test_capture.py
 ``` ImportError: /home/ubuntu/ww/rtsp_hw_decode/test/decode.so: undefined symbol: cvtColor```

**Comment by ZCcaptain** [comment]
注意增加makefile下对.cu文件的配置

**Comment by feifeiwei** [comment]
好了 ，非常感谢～～
